### ISSUE TITLE
There is no test .py for this code？

### ISSUE THREAD

**Issue by pupu-chenyanyan** [shachoi/HANet#10]
how to do a test？ scripts / submit?

**Comment by sunghac** [comment]
You can find them at the following link:
https://github.com/shachoi/HANet#inference
https://github.com/shachoi/HANet#submit-to-cityscapes-benchmark-server

**Comment by pupu-chenyanyan** [comment]
> You can find them at the following link:
> https://github.com/shachoi/HANet#inference
> https://github.com/shachoi/HANet#submit-to-cityscapes-benchmark-server
thank your reply very much !  I do a test, but i find the speed about 17s/ per image... two slow ?!
How fast were you running? I can't find this information in the article .

**Comment by sunghac** [comment]
If you change the inference method “sliding” into “pooling”, it is much faster. But, sliding method is more accurate.
Additionally, “pooling with no scaling” is most fastest option.
