### ISSUE TITLE
about parameter

### ISSUE THREAD

**Issue by huixiancheng** [shachoi/HANet#12]
Great work!thx for the open source:thumbsup:
However,I hava some problems about the paras.
how to get the parameter “hanet_set”  "hanet_pos" "pos_rfactor" "no_pos_dataset"  
and what's about their meaning
https://github.com/shachoi/HANet/blob/1d478fb4d477041a75bdd669e37cc80d63d975eb/scripts/train_r101_os8_hanet_best.sh#L26-L28
is it  just like (pos_h, pos_w) come from statistical approach to the dataset?
https://github.com/shachoi/HANet/blob/1d478fb4d477041a75bdd669e37cc80d63d975eb/datasets/cityscapes.py#L642-L697

w/o the para "pos_h, pos_w" will influence the effect of  Hanet? and could you tell me the way to get the para from other dataset?

**Comment by sunghac** [comment]
Sorry for the delayed response and omitted code description :)
1. --hanet_set **3 64 3** \ # these parameters are related to the convolution architecture of HANet. The kernel size in convolution layers at HANet is **3**, the channel reduction ratio is **64** (denominator is 64), and the number of layer of convolution in HANet is **3**. Please refer to the following paragraph in our paper.
![image](https://user-images.githubusercontent.com/34509882/104874151-8cabca80-5995-11eb-8ca7-e69777771311.png)
2. --hanet_pos 2 1 \ # these parameters means how to inject positional information into the convolutional layers in HANet. The positional information is injected into **2**nd layer among the convolutional layers and 1 means positional encoding, not positional embedding. (i.e. 1: sinusoidal version positional encoding, 0: learnable positional embedding)
3. --pos_rfactor **8** \ # this parameter means the resolution of positional information. Position information is initially set to from 0 to 127, and it is reduced to from 0 to 15 using the **8** as denominator. Please find the related paragraph in our paper as follows.
"128//pos_rfactor"
![image](https://user-images.githubusercontent.com/34509882/104874906-6424d000-5997-11eb-9d76-3c3a91f3571e.png)

Additionally, pos_w is not used in our code. 
Position information is injected with 0 for the top part of the entire image and 15 for the bottom part. (when the pos_rfactor is set to 8). When the image is cropped, the positional information at the top will be 0 or more.

**Comment by huixiancheng** [comment]
Received:thumbsup:
