### ISSUE TITLE
What's the meaning of attention_loss?

### ISSUE THREAD

**Issue by huixiancheng** [shachoi/HANet#16]
Dear Sir.
As mentioned in the question. And How to caculate this? Wil this improve the results? It looks like you didn't use it in the training？

**Comment by sunghac** [comment]
Hi,
As you mentioned, the attention loss was tested while conducting various experiments, but in the end, it was not used.
The ground truth of the attention is calculated from the below code:
https://github.com/shachoi/HANet/blob/1d478fb4d477041a75bdd669e37cc80d63d975eb/train.py#L587

**Comment by huixiancheng** [comment]
Thanks a lot
