### ISSUE TITLE
Why we need cross the segmentation main networks to gain attention?

### ISSUE THREAD

**Issue by huixiancheng** [shachoi/HANet#17]
Hi. Dear Sir. I'm still confused as to why we need to cross a blocks to multiply the attention map？
This is your pipeline and HANet model. As stated in the paper， there are lower- and higher-level feature maps in semantic seg-
mentation networks
![Inked微信截图_20210822010818_LI](https://user-images.githubusercontent.com/65054204/130330122-c29e90bb-d38f-4149-aa8c-13805d2db730.jpg)
![Inked微信截图_20210822013128_LI](https://user-images.githubusercontent.com/65054204/130330296-33b2541a-1e9c-4650-a237-e74b2b18f439.jpg)

I want to now why we can't  get attention in one feature like what SENET have done. 

Is there any iimplied meaning behind this or has it been experimentally proven to be ineffective?
![v2-c76deb24c36a504b917c5abd71b86016_b](https://user-images.githubusercontent.com/65054204/130330035-db04609e-fe2d-453f-b63b-5d5713c09ec2.jpg)

**Comment by sunghac** [comment]
@huixiancheng 
Thanks for the detailed description and question. I think that's a good point.
We initially experimented with multiplying the attention map on the same layer as in SENet. I believe it was an architectural choice, so we chose the better one experimentally. However, further exploration in SENet-like structures may be required.

**Comment by huixiancheng** [comment]
Thanks a lot！:ok_hand:
