### ISSUE TITLE
Bad results on the cityscapes test dataset

### ISSUE THREAD

**Issue by LeiGan0215** [shachoi/HANet#2]
Dear shachoi:
    I download your model on the google drive which you provide,I use the model HANet_r101_os8_city_0.80293.pth,it achieves 82.05 miou on the cityscapes val dataset,which is the same as you write in the paper.But when I use the model for test by the submit_r101_os8.sh you provide,and submit the res in the pred folder to the server,it can only achieve 72.09 miou，it's too low...so I just want to ask why this happened?

**Comment by sunghac** [comment]
Thank you for your attention to our work.

The channel reduction ratio r specified in the submit script was incorrect. When I train the ResNet-101-OS8, I set the reduction ratio as 64. However, the ratio in the submit script was wrong as 32. So I modified it as the following figure.
![image](https://user-images.githubusercontent.com/34509882/85532770-f0158a00-b64a-11ea-8360-2be04c7cc456.png)

If you have any other questions, feel free to ask.

Thanks!
Sungha.
