### ISSUE TITLE
hi,I'm using the hanet you provided_ r101_ os8_ city_ 0.80293.pth model try Eval_ r101_ Os8.sh, but there are some problems

### ISSUE THREAD

**Issue by zyshawn** [shachoi/HANet#4]
![QQ截图20200917125152](https://user-images.githubusercontent.com/48002141/93421943-37778380-f8e5-11ea-8833-7a9f9938db45.png)
How to solve this problem? thank you!

**Comment by sunghac** [comment]
Hi,
I tried again, and it worked well.

Can you check the package dependencies?

conda create --name hanet python=3.6
conda activate hanet
conda install -y pytorch=1.4.0 torchvision=0.5.0 cudatoolkit=10.1 -c pytorch
conda install scipy==1.4.1
conda install tqdm==4.46.0
conda install scikit-image==0.16.2
pip install tensorboardX==2.0
pip install thop
pip install opencv-python==4.4.0.42

![image](https://user-images.githubusercontent.com/34509882/93437479-fee8a180-f906-11ea-861b-1043f9a2fc2d.png)

**Comment by zyshawn** [comment]
I tried it and I still can't. is it related to the system? My OS name is Ubuntu 18.04. Can your project files only run in OS win?

I tested on the colab and configured your environment, but I still reported the same error as above

**Comment by zyshawn** [comment]
> Hi,
> I tried again, and it worked well.
> 
> Can you check the package dependencies?
> 
> conda create --name hanet python=3.6
> conda activate hanet
> conda install -y pytorch=1.4.0 torchvision=0.5.0 cudatoolkit=10.1 -c pytorch
> conda install scipy==1.4.1
> conda install tqdm==4.46.0
> conda install scikit-image==0.16.2
> pip install tensorboardX==2.0
> pip install thop
> pip install opencv-python==4.4.0.42
> 
> ![image](https://user-images.githubusercontent.com/34509882/93437479-fee8a180-f906-11ea-861b-1043f9a2fc2d.png)

thank you！I have solved it！

**Comment by sunghac** [comment]
Good job! Thanks
