### ISSUE TITLE
cityscapes 主要檔案內容

### ISSUE THREAD

**Issue by Shaiken** [shachoi/HANet#5]
因為想用自己的資料來訓練
所以想問問組成tfrecord的那些資料是什麼
有先載gtFine
但沒載leftImg8bit(太大了)
可以問一下train/test/val底下的照片是.png原始rgb影像嗎
cityscapes
 └ leftImg8bit_trainvaltest
   └ leftImg8bit
     └ train
     └ val
     └ test
 └ gtFine_trainvaltest
   └ gtFine
     └ train
     └ val
     └ test

**Comment by sunghac** [comment]
Sorry, but I can't understand your question well.
As far as I understood your question, the Cityscapes dataset includes png files.

Thanks!
