### ISSUE TITLE
About Ablation Studies of Coordconv

### ISSUE THREAD

**Issue by Sibyl233** [shachoi/HANet#6]
Hi, sorry to bother. I want to confirm some details about the ablation studies in your paper concerning Coordconv. It says:

>  To compare with CoordConv [26], we conduct experiments by replacing standard convolutional layers after the backbone with CoordConv.

1. Does it mean in this experiment you only replace the 2 convolution layers after ASPP(in the decoder)？
2. If so, why only replace the standard convolutions in decoder instead of encoder？

**Comment by sunghac** [comment]
Sorry to delay response.

We put Coordconv in the same layer to which the HANet module was added.
The reason why HANet was added to the decoder part, which **is after the final layer of ResNet (e.g. from ASPP)** is that the channel attention according to the vertical position was more useful in the high-level feature representation.
I think you can try to add CoordConv in the encoder layer.

Thanks!
