### ISSUE TITLE
how to change SyncBatchNorm?

### ISSUE THREAD

**Issue by MrCrazyCrab** [shachoi/HANet#7]
i want to try the model on windows which is not supported to the distrubution. And i change the 
`net = torch.nn.SyncBatchNorm.convert_sync_batchnorm(net)` into 
`net =  torch.nn.BatchNorm2d(net)`
but i got a error which is "TypeError: new(): data must be a sequence (got DeepV3PlusHANet)".
And what should i do to run the code on windows, and how to change SyncBatchNorm with BatchNorm2d?

**Comment by sunghac** [comment]
Sorry for delay response.

"torch.nn.SyncBatchNorm.convert_sync_batchnorm"
this function takes the entire networks ("net"), converts standard batchnorm in networks into sync batchnorm, and returns the entire networks.
So you just delete net = "torch.nn.SyncBatchNorm.convert_sync_batchnorm(net)"
and not add "net = torch.nn.BatchNorm2d(net)"

Thanks!

**Comment by Gzn520** [comment]
如何解决？subprocess.CalledProcessError: Command '['/home/user/anaconda3/envs/hanet/bin/python', '-u', 'train.py', '--local_rank=0', '--dataset', 'cityscapes', '--arch', 'network.deepv3.DeepR101V3PlusD_HANet_OS8', '--city_mode', 'trainval', '--lr_schedule', 'poly', '--lr', '0.01', '--poly_exp', '0.9', '--hanet_lr', '0.01', '--hanet_poly_exp', '0.9', '--max_cu_epoch', '10000', '--class_uniform_pct', '0.5', '--class_uniform_tile', '1024', '--syncbn', '--sgd', '--crop_size', '864', '--scale_min', '0.5', '--scale_max', '2.0', '--rrotate', '0', '--color_aug', '0.25', '--gblur', '--max_iter', '90000', '--bs_mult', '3', '--hanet', '1', '1', '1', '1', '0', '--hanet_set', '3', '64', '3', '--hanet_pos', '2', '1', '--pos_rfactor', '8', '--dropout', '0.1', '--pos_noise', '0.5', '--aux_loss', '--cls_wt_loss', '--date', '0101', '--exp', 'r101_os8_hanet_best', '--ckpt', './logs/', '--tb_path', './logs/']' returned non-zero exit status 1

**Comment by MrCrazyCrab** [comment]
@shachoi  thanks for you reply, i have tried that , and it won't work.

**Comment by sunghac** [comment]
@MrCrazyCrab 
Additionally, you should remove "--syncbn \" from training script.
Please refer to the following link.
https://github.com/shachoi/HANet/blob/1d478fb4d477041a75bdd669e37cc80d63d975eb/config.py#L100

Thanks
